title = "Charlie Pitkin"
baseURL = "https://charliepitkin.com"
tags = ["projects", "open source", "posts"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "I'm Charlie, Devops Engineer + open source enthusiast"
    author = "Charlie Pitkin"
    description = "All the things!"
    logoBig = "/img/osaka-castle.png"
    logoSmall = "/img/osaka-castle_400x400.jpg"
    favicon = "icon.ico"
    opengraphImage = "/img/osaka-castle_400x400.jpg"
    twitter = "charlespitkin"
    linkedin = "cpitkin"
    github = "cpitkin"
    email = ""
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = false

# [[menu.main]]
#     name = "About"
#     url  = "/about"
#     weight = 1
[[menu.main]]
    name = "blog"
    url  = "/blog"
    weight = 1
# [[menu.main]]
#     name = "Contact"
#     url  = "/contact"
#     weight = 4
