baseURL = "https://charliepitkin.com/"
languageCode = "en-us"
theme = "minimal"
title = "Charlie Pitkin"
[[menu.icon]]
name = "linkedin"
url = "https://www.linkedin.com/in/charlie-pitkin-b1701423/"
weight = 4
[[menu.icon]]
name = "twitter"
url = "https://twitter.com/charlespitkin/"
weight = 3
[[menu.icon]]
name = "github"
url = "https://github.com/cpitkin/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
accent = "white"
author = "Charlie Pitkin"
backgroundcolor = "black"
description = "more coming soon ..."
font = "Raleway"
githubusername = "cpitkin"
highlight = true
highlightlanguages = ["javascript", "shell"]
highlightstyle = "solarized-dark"
showborder = true
