baseURL = "https://charliepitkin.com/"
languageCode = "en-us"
theme = "minimal"
title = "Charile Pitkin"
[[menu.main]]
name = "Posts"
url = "/post/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
accent = "black"
author = "Charlie Pitkin"
backgroundcolor = "white"
description = "more coming soon ..."
# font = "Raleway"
font = "news cycle"
githubusername = "cpitkin"
highlight = true
highlightlanguages = ["javascript", "bash", "puppet", "json", "yaml"]
highlightstyle = "hybrid"
showborder = true
