baseurl = "https://charliepitkin.com"

# Theme information
languageCode = "en"
theme = "hello-friend-ng"
defaultTheme = "dark"

# Default directory names for templates
contentTypeName = "posts"

# Syntax highlighting - https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true
# PygmentsStyle = "monokai"

# RSS settings
disableRSS = false
rssLimit  = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

# General settings
enableRobotsTXT = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

# Enable Git commit links in posts
enableGitInfo = true
gitUrl = "https://github.com/cpitkin/website" # Prefix of link to the git commit detail page

# Parameters to configure general site look and feel
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/CharlesPitkin"
  [[params.social]]
    name = "github"
    url  = "https://github.com/cpitkin"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/cpitkin/"

  # Open Graph & Twitter cards - https://gohugo.io/templates/internal/#configure-open-graph
  description = "My small corner of the Internet"
  images = ["feature-image.jpg"]

  # How we group content
  [taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

# Set language and home page content
DefaultContentLanguage = "en"
[languages]
  [languages.en]
    title = "Charlie Pitkin"
    homeSubtitle = "Automation - Open Source Software - Gaming - Travel"
    keywords = "DevOps,Programming,Automation,Gaming,Open Source Software,Travel"
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ /home/cpitkin"
      logoHomeLink = "/"
    # path = "/img/kodai-ji-garden.png"
    # alt = "Your example logo alt text"

    # The en language menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
