baseURL = "https://charliepitkin.com/"
languageCode = "en-us"
theme = "minimal"
title = "Charile Pitkin"
[[menu.main]]
name = "Posts"
url = "/post/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
accent = "black"
author = "Charlie Pitkin"
backgroundcolor = "white"
description = "more coming soon ..."
font = "Raleway"
githubusername = "cpitkin"
highlight = true
highlightlanguages = ["go", "haskell", "kotlin", "scala", "swift", "javascript", "shell"]
highlightstyle = "solarized-dark"
showborder = true
