baseURL = "https://charliepitkin.com/"
languageCode = "en-us"
theme = "minimal"
title = "Charile Pitkin"
[[menu.icon]]
name = "stack-overflow"
url = "https://stackoverflow.com/users/7138991/charlie-pitkin"
weight = 4
[[menu.icon]]
name = "linkedin"
url = "https://www.linkedin.com/in/charlie-pitkin-b1701423/"
weight = 3
[[menu.icon]]
name = "twitter"
url = "https://twitter.com/charlespitkin/"
weight = 2
[[menu.icon]]
name = "github"
url = "https://github.com/cpitkin/"
weight = 1
[[menu.main]]
name = "Projects"
url = "/project/"
weight = 3
[[menu.main]]
name = "Posts"
url = "/post/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
accent = "black"
author = "Charlie Pitkin"
backgroundcolor = "white"
description = "more coming soon ..."
font = "News Cycle"
githubusername = "cpitkin"
highlight = true
highlightlanguages = ["javascript", "bash", "puppet", "json", "yaml"]
highlightstyle = "hybrid"
showborder = true
