[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.55.6"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.55.6"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.6"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.55.6"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/blog"
  to = "/posts"
  status = 301
  force = false
[[redirects]]
  from = "/install-graylog-on-freebsd"
  to = "/posts/technology/install-graylog-on-freebsd"
  status = 301
  force = false
[[redirects]]
  from = "/posts/new-site/"
  to = "/posts/news/new-site/"
  status = 301
  force = false
[[redirects]]
  from = "/posts/automated-video-transcoding-with-openfass"
  to = "/posts/technology/automated-video-transcoding-with-openfass"
  status = 301
  force = false
[[redirects]]
  from = "/posts/install-graylog-on-freebsd"
  to = "/posts/technology/install-graylog-on-freebsd"
  status = 301
  force = false
[[redirects]]
  from = "/posts/redirect-test-release"
  to = "/posts/technology/redirect-test-release"
  status = 301
  force = false
[[redirects]]
  from = "/posts/setup-openfaas-nomad"
  to = "/posts/technology/setup-openfaas-nomad"
  status = 301
  force = false
[[redirects]]
  from = "/travels/map"
  to = "https://nomadlist.com/@cpitkin"
  status = 200
